apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldpinger
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bloomberg/goldpinger.git
    chart: charts/goldpinger
    targetRevision: 1.0.1