apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldpinger
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bloomberg/goldpinger
    chart: charts/goldpinger
    targetRevision: 1.0.1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
