apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldpinger
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.github.io/charts
    chart: goldpinger
    targetRevision: 3.0.1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
