apiVersion: v1
kind: Service
metadata:
  name: minio-node-port
spec:
  type: NodePort
  selector:
    app: minio
  destination:
    namespace: minio-dev
  ports:
  - name: http
    port: 80
    targetPort: 9000
    nodePort: 30009
    protocol: TCP
  - name: https
    port: 443
    targetPort: 9001
    nodePort: 30010
    protocol: TCP
